analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4623656
  brandStrength: 0.109319
  lightness: 0.9923388
  brandColors:
    - '#FEFEFE'
    - '#016DA4'
    - '#0BBFDF'
    - '#2F7678'
    - '#0D2727'
  rhythmicContrast: 0.2043011
typography_spectrum: 0.3398166948463768
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9050179
favicon: null
name: Paula Manacas
